### ISSUE TITLE
Failed to execute script 

### ISSUE THREAD

**Issue by gonS0u** [MetadataForensics/Google-Location-History-Data-Parser#1]
Hello, I tried this very useful program and had problems.

![image](https://github.com/MetadataForensics/Google-Location-History-Data-Parser/assets/52167323/11d52d92-7644-456d-a6fc-cadc6e05c120)

**Comment by MetadataForensics** [comment]
Good Evening, Thank you for your feedback! We apologize for the error, this issue should be fixed now. Please uninstall (using the unins000 application within C:\Program Files\Metadata Forensics\Google Location History Data Parser if installed in default location) and use our new Setup, uploaded now for Version 1.0.1.6. Thanks again, please let us know if you run into any other issues!

**Comment by gonS0u** [comment]
Hi, I did what you said and now I have another issue.

![image](https://github.com/MetadataForensics/Google-Location-History-Data-Parser/assets/52167323/cc17be87-fb91-4190-8f0f-fe81acc982a5)

**Comment by MetadataForensics** [comment]
I apologize you've run into another issue. Thank you for the feedback - I am looking into this matter but understand it can be frustrating as the user as well. With the naming convention of your takeout file it appears to have been captured on 4/25, which would put it into the format that has been supported since version 1.0.1.4. Have you been able to process your Google Takeout Location History (Timeline) data through anything else, such as RLEAPP?

**Comment by gonS0u** [comment]
Yes, in RLEAPP I had a problem with python, I tried to install 2 different versions of python and it gave the same error.

![image](https://github.com/MetadataForensics/Google-Location-History-Data-Parser/assets/52167323/2d57e472-2f02-44fd-9235-ed99a9d867fa)

**Comment by MetadataForensics** [comment]
Understood, that error is also due to an update. I’ve been a bit fan of the LEAPPs for some time and always recommend downloading a new version each time you attempt to process with it to verify all your artifacts are up to date. That specific error is because of a required artifact update.

**Comment by MetadataForensics** [comment]
Finally, I have run into the same error within my testing and was able to create a solution! Please download and attempt to run your data against our newest upload - Version 1.0.1.7. If this solution is successful, and more importantly if not, please let me know.

**Comment by gonS0u** [comment]
Yes I confirm, I don't have the error. Thank you very much!

**Comment by MetadataForensics** [comment]
Outstanding, thank you for the confirmation! Please let us know if you run into any issues with this tool in the future.
